# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-23 00:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appartient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'appartient',
            },
        ),
        migrations.CreateModel(
            name='Contient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'contient',
            },
        ),
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('idcours', models.AutoField(db_column='IDCours', primary_key=True, serialize=False)),
                ('intitulecours', models.CharField(blank=True, db_column='IntituleCours', max_length=25, null=True)),
                ('debutcours', models.DateTimeField(blank=True, db_column='DebutCours', null=True)),
                ('fincours', models.DateTimeField(blank=True, db_column='FinCours', null=True)),
            ],
            options={
                'db_table': 'Cours',
            },
        ),
        migrations.CreateModel(
            name='Enseigne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomsalle', models.CharField(blank=True, db_column='NomSalle', max_length=25, null=True)),
                ('idcours', models.ForeignKey(db_column='IDCours', on_delete=django.db.models.deletion.DO_NOTHING, to='Appli.Cours')),
            ],
            options={
                'db_table': 'enseigne',
            },
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('idetud', models.AutoField(db_column='IDEtud', primary_key=True, serialize=False)),
                ('nometud', models.CharField(blank=True, db_column='NomEtud', max_length=25, null=True)),
                ('prenometud', models.CharField(blank=True, db_column='PrenomEtud', max_length=25, null=True)),
                ('mailetud', models.CharField(blank=True, db_column='MailEtud', max_length=50, null=True)),
                ('hasbadged', models.IntegerField(blank=True, db_column='hasBadged', null=True)),
                ('tracenfc', models.CharField(blank=True, db_column='TraceNFC', max_length=25, null=True)),
            ],
            options={
                'db_table': 'Etudiant',
            },
        ),
        migrations.CreateModel(
            name='Fiche',
            fields=[
                ('idfiche', models.AutoField(db_column='IDFiche', primary_key=True, serialize=False)),
                ('valide', models.IntegerField(blank=True, db_column='Valide', null=True)),
            ],
            options={
                'db_table': 'Fiche',
            },
        ),
        migrations.CreateModel(
            name='Groupe',
            fields=[
                ('idgroupe', models.AutoField(db_column='IDGroupe', primary_key=True, serialize=False)),
                ('intitulegroupe', models.CharField(blank=True, db_column='IntituleGroupe', max_length=25, null=True)),
            ],
            options={
                'db_table': 'Groupe',
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('idpromo', models.AutoField(db_column='IDPromo', primary_key=True, serialize=False)),
                ('intitulepromo', models.CharField(blank=True, db_column='IntitulePromo', max_length=25, null=True)),
            ],
            options={
                'db_table': 'Promotion',
            },
        ),
        migrations.CreateModel(
            name='Trace',
            fields=[
                ('tracenfc', models.CharField(db_column='TraceNFC', max_length=25, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Trace',
            },
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('idutil', models.AutoField(db_column='idUtil', primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=25, null=True)),
                ('last_name', models.CharField(blank=True, max_length=25, null=True)),
                ('password', models.CharField(blank=True, max_length=75, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('username', models.CharField(blank=True, max_length=25, null=True)),
                ('issuperuser', models.IntegerField(blank=True, db_column='isSuperuser', null=True)),
                ('isscanning', models.IntegerField(blank=True, db_column='isScanning', null=True)),
                ('tracenfc', models.CharField(blank=True, db_column='TraceNFC', max_length=25, null=True)),
                ('validationkey', models.CharField(blank=True, db_column='ValidationKey', max_length=100, null=True)),
                ('validated', models.IntegerField(blank=True, db_column='Validated', null=True)),
                ('hasbadged', models.IntegerField(blank=True, db_column='hasBadged', null=True)),
            ],
            options={
                'db_table': 'Utilisateur',
            },
        ),
        migrations.AddField(
            model_name='etudiant',
            name='idpromo',
            field=models.ForeignKey(blank=True, db_column='IDPromo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Appli.Promotion'),
        ),
        migrations.AddField(
            model_name='enseigne',
            name='idfiche',
            field=models.ForeignKey(db_column='IDFiche', on_delete=django.db.models.deletion.DO_NOTHING, to='Appli.Fiche'),
        ),
        migrations.AddField(
            model_name='enseigne',
            name='idutil',
            field=models.ForeignKey(db_column='idUtil', on_delete=django.db.models.deletion.CASCADE, to='Appli.Utilisateur'),
        ),
        migrations.AddField(
            model_name='cours',
            name='idgroupe',
            field=models.ForeignKey(blank=True, db_column='IDGroupe', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Appli.Groupe'),
        ),
        migrations.AddField(
            model_name='contient',
            name='idetud',
            field=models.ForeignKey(db_column='IDEtud', on_delete=django.db.models.deletion.DO_NOTHING, to='Appli.Etudiant'),
        ),
        migrations.AddField(
            model_name='contient',
            name='idfiche',
            field=models.ForeignKey(db_column='IDFiche', on_delete=django.db.models.deletion.DO_NOTHING, to='Appli.Fiche'),
        ),
        migrations.AddField(
            model_name='appartient',
            name='idetud',
            field=models.ForeignKey(db_column='IDEtud', on_delete=django.db.models.deletion.CASCADE, to='Appli.Etudiant'),
        ),
        migrations.AddField(
            model_name='appartient',
            name='idgroupe',
            field=models.ForeignKey(db_column='IDGroupe', on_delete=django.db.models.deletion.DO_NOTHING, to='Appli.Groupe'),
        ),
        migrations.AlterUniqueTogether(
            name='enseigne',
            unique_together=set([('idcours', 'idutil', 'idfiche')]),
        ),
        migrations.AlterUniqueTogether(
            name='contient',
            unique_together=set([('idfiche', 'idetud')]),
        ),
        migrations.AlterUniqueTogether(
            name='appartient',
            unique_together=set([('idgroupe', 'idetud')]),
        ),
    ]
